export const MONTHS = [
  { label: "Month", value: "none" },
  { label: "January", value: "01" },
  { label: "February", value: "02" },
  { label: "March", value: "03" },
  { label: "April", value: "04" },
  { label: "May", value: "05" },
  { label: "June", value: "06" },
  { label: "July", value: "07" },
  { label: "August", value: "08" },
  { label: "September", value: "09" },
  { label: "October", value: "10" },
  { label: "November", value: "11" },
  { label: "December", value: "12" },
];
export const YEARS = [
  { label: "Year", value: "none" },
  { label: "2023", value: "23" },
  { label: "2024", value: "24" },
  { label: "2025", value: "25" },
  { label: "2026", value: "26" },
  { label: "2027", value: "27" },
  { label: "2028", value: "28" },
  { label: "2029", value: "29" },
  { label: "2030", value: "30" },
  { label: "2031", value: "31" },
  { label: "2032", value: "32" },
  { label: "2033", value: "33" },
  { label: "2034", value: "34" },
];
